services:
  spark-master:
    image: sparkkubetest:local
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master     
    ports:
      - "7077:7077"  # Spark Master port for worker communication
      - "8080:8080"  # Spark Master Web UI
      

  spark-worker:
    image: sparkkubetest:local
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    ports:
      - "8082:8082"  # Spark Worker Web UI