services:
  spark-master:
    image: sparkkubetestmaster:4.0.1
    container_name: spark-master
    hostname: spark-master
    entrypoint: ["/usr/local/bin/entrypoint-master.sh"]
    ports:
      - "7077:7077"   # Spark master RPC
      - "8080:8080"   # Spark master UI

  spark-worker:
    image: sparkkubetestmaster:4.0.1
    container_name: spark-worker
    hostname: spark-worker
    entrypoint: ["/usr/local/bin/entrypoint-worker.sh"]
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"